config/routes.rb
Rails.application.routes.draw do
  root "courses#index"
  get "about", to: "pages#about"
  get "login", to: "logins#new"
  post "login", to: "logins#create"
  delete "logout", to: "logins#destroy"
  post "course_enroll", to: "enrollments#create"
  resources :courses, only: [:show, :new]
  resources :students, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  has_many :enrollments
  has_many :students, through: :enrollments
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_many :enrollments
  has_many :courses, through: :enrollments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_user
  helper_method :current_user, :logged_in?

  def logged_in?
    !!current_user
  end
  
  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user, only: [:index]

  def index
    @courses = Course.all
  end

  def new
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def create
    course_to_add = Course.find(enrollment_params[:course_id])
    unless current_user.courses.include?(course_to_add)
      Enrollment.create(course: course_to_add, student: current_user)
      flash[:notice] = "You have successfully enrolled in #{course_to_add.name}"
      redirect_to current_user
    else
      flash[:alert] = "Something was wrong with your enrollment"
      redirect_to root_path
    end
  end

  private
  
  def enrollment_params
    params.permit([:course_id])
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]

  def new
  end

  def create
    student = Student.find_by(email: session_params[:email].downcase)
    if student && student.authenticate(session_params[:password])
      flash[:notice] = "You have successfully logged in"
      session[:student_id] = student.id
      redirect_to student
    else
      flash.now[:alert] = "Something was wrong with your login information"
      render :new
    end
  end
  
  def destroy
    session[:student_id] = nil
    flash[:notice] = "You have successfully logged out"
    redirect_to root_path
  end
  
  private

  def session_params
    params.require(:logins).permit(:email, :password)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user, only: [:about]

  def about
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :set_student, only: [:show, :edit, :update]
  before_action :require_same_student, only: [:edit, :update]
  
  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = "You have successfully signed up"
      redirect_to @student
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:notice] = "You have successfully updated your profile"
      redirect_to @student
    else
      render :edit
    end
  end

  private
  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def require_same_student
    if current_user != @student
      flash[:alert] = "You can only edit your own profile"
      redirect_to student_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def session_link
    if logged_in?
      button_to("Logout", logout_path, method: :delete, form_class: "valign-wrapper", class: "btn-flat waves-effect valign-wrapper")
    else
      link_to("Login", login_path)
    end
  end
end

app/views/courses/_course.html.erb
<div class="col s6 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
      <p><%= course.description %></p>
    </div>
    <div class="card-action">
      <div class="row card-action-row">
        <% if logged_in? && !current_user.courses.include?(course) %>
          <%= button_to "Enroll", course_enroll_path(course_id: course.id), method: :post, form_class: "col s3", class: "btn-flat waves-effect orange-text text-lighten-1" %>
        <% end %>
        <%= button_to "Info", course_path(course), form_class: "col s3", class: "btn-flat waves-effect orange-text text-lighten-1" %>
      </div>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Course Listing</h3>
  </div>
</div>
<div class="row">
  <%= render @courses %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |name, message| %>
  <div class="container">
    <div class="row">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2" id="fade-out-target">
          <span class="white-text">
            <%= message %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech U</h5>
        <p class="grey-text text-lighten-4">The future of development training</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><%= link_to "Help", nil, class: "grey-text text-lighten-3" %></li>
          <li><%= link_to "About", about_path, class: "grey-text text-lighten-3" %></li>
          <li><%= link_to "Contact Us", nil, class: "grey-text text-lighten-3" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2022 Tech U
      <%= link_to "About", about_path, class: "grey-text text-lighten-4 right" %>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Account Dropdown (Regular) -->
<ul id="dropdown1" class="dropdown-content">
  <li><%= session_link %></li>
  <% if logged_in? %>
    <li><%= link_to "Profile", student_path(current_user) %></li>
  <% end %>
</ul>
<!-- Account Dropdown (Hamburger) -->
<ul id="dropdown2" class="dropdown-content">
  <li><%= session_link %></li>
  <% if logged_in? %>
    <li><%= link_to "Profile", student_path(current_user) %></li>
  <% end %>
</ul>
<!-- Hamburger Menu -->
<ul class="sidenav" id="mobile-demo">
  <li><%= link_to "Courses", root_path %></li>
  <% if logged_in? %>
    <li><%= link_to "Students", students_path %></li>
  <% end %>
  <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
</ul>
<nav>
  <div class="nav-wrapper">
    <div class="container">
      <%= link_to "Tech U", root_path, class: "brand-logo right" %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><%= link_to "Courses", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Students", students_path %></li>
        <% end %>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech U</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <header>
      <%= render "layouts/navbar" %>
      <%= render "layouts/flash" %>
    </header>
    <main class="container">
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="center-align">Login</h3>
        <div class="row">
          <%= form_for(:logins, html: {class: "col s12" }, data: { turbo: false }) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :email, placeholder: "Enter your email address", autofocus: true %>
                <%= f.label :email %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: "Enter your password" %>
                <%= f.label :password, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.button class: "btn orange waves-effect waves-light right" do %>
                  <i class="material-icons right">arrow_forward</i>Login
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong><%= pluralize(obj.errors.count, "error") %> prohibited your profile from being created</strong>
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render "shared/errors", obj: @student %>
<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="center-align"><%= @student.new_record? ? "Sign up!" : "Edit your profile"%></h3>
        <div class="row">
          <%= form_for(@student, html: {class: "col s12" }, data: { turbo: false }) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter your full name", autofocus: true %>
                <%= f.label :name, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :email, placeholder: "Enter your email address" %>
                <%= f.label :email, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: "Choose a password" %>
                <%= f.label :password, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password_confirmation, placeholder: "Confirm your password" %>
                <%= f.label :password_confirmation, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.button class: "btn orange waves-effect waves-light right" do %>
                  <i class="material-icons right">arrow_forward</i><%= @student.new_record? ? "Sign Up" : "Submit Updates" %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/_student.html.erb
<div class="col s6 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title">Name: <%= student.name %></span>
      <p>Email: <%= student.email %></p>
      <p>Course Enrollments: 
        <% if student.courses.empty? %>
          None
        <% else %>
          <ul>
            <% student.courses.each do |course| %>
              <li><%= course.name %></li>
            <% end %>
          </ul>
        <% end %>
      </p>
    </div>
    <div class="card-action">
      <%= link_to "View Profile", student_path(student) %>
    </div>
  </div>
</div>

app/views/students/_student_full.html.erb
<div class="col s6 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title">Name: <%= student.name %></span>
      <p>Email: <%= student.email %></p>
      <p>Course Enrollments: 
        <% if student.courses.empty? %>
          None
        <% else %>
          <ul>
            <% student.courses.each do |course| %>
              <li><%= course.name %></li>
            <% end %>
          </ul>
        <% end %>
      </p>
    </div>
    <%if current_user == @student %>
      <div class="card-action">
        <%= link_to '<i class="material-icons right">create</i>Edit your profile'.html_safe, edit_student_path(student), class: "btn waves-effect waves-light" %>
      </div>
    <% end %>
  </div>
</div>

app/views/students/edit.html.erb
<%= render "form" %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Student Listing</h3>
  </div>
</div>
<div class="row">
  <%= render @students %>
</div>

app/views/students/new.html.erb
<%= render "form" %>

app/views/students/show.html.erb
<div class="row sign-up-form">
  <%= render "student_full", student: @student %>
</div>